POST https://localhost:5001/api/pagamento/create
Content-Type: application/json

{
    "tipoPagamento" : "Dinheiro",
    "descricao" : "À vista"
}

### Criar outra forma de pagamento
POST https://localhost:5001/api/pagamento/create
Content-Type: application/json

{
    "tipoPagamento" : "PIX",
    "descricao" : "À vista"
}
### Criar mais uma forma de pagamento
POST https://localhost:5001/api/pagamento/create
Content-Type: application/json

{
    "tipoPagamento" : "Cartão",
    "descricao" : "À vista"
}
### Listar
GET https://localhost:5001/api/pagamento/list

