### Listar vendas
GET https://localhost:5001/api/venda/list

### Criar vendas

POST https://localhost:5001/api/venda/create
Content-Type: application/json

{
    "Cliente" : "Bigu",
    "FormaPagamentoId" : 2,
    "Itens" : [
        {
            "ProdutoId" : 1,
            "Quantidade" : 1,
            "Preco" : 20,
            "CarrinhoId" : ""
        },
        {
            "ProdutoId" : 2,
            "Quantidade" : 5,
            "Preco" : 35,
            "CarrinhoId" : ""
        }
    ]
}